# -*- coding: utf-8 -*-
"""hipotenusa.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MmpfJQ-y09EZYrpahzzPx_sqY9aP1GXM
"""

import math

H: float;

A = float(input("Digite o valor de A:"))
B = float (input("Digite o valor de B:"))

H = math.sqrt(A**2 + B**2)

print(f"O valor da hipotenusa é {H:.2f}")