# -*- coding: utf-8 -*-
"""aula_01_estrutura_de_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_aAyYDGaU0jBmx1jJhZ8Us6kjruW7nO
"""

#Tuplas

mamiferos = ("Leão", "Humano", "Cachorro" , "Leão")
insetos = ("Louva_Deus", "Besouro", "Mosca")

#União das duas tuplas
uniao_MI = mamiferos + insetos

print(uniao_MI)

#Listas

mamiferos = ["Leão", "Humano", "Cachorro" , "Leão"]
insetos = ["Louva Deus", "Besouro", "Mosca"]

#União Listas

uniao_MI = mamiferos + insetos

#Adicionar elemento na lista

uniao_MI.append("Gato")
print(uniao_MI)

#Dicionário
dicionario1 = {"João": 20, "Maria": 30, "Pedro": 35, "Júlia": 18}

#Visualiza os itens
dicionario1.items()

#Mostra as chaves do dicionário
dicionario1.keys()


#Criação do 2°Dicionário
dicionario2 = {"José": 22, "Paulo": 33}

#Adiciona o 2°Dicionário no 1°Dicionário
dicionario1.update(dicionario2)

print(dicionario1)

#Conjuntos

c1 = {1,2,3,4,5}
c2 = {3,4,5,6,7}

#Interseção dos conjuntos
c2.intersection(c1)

#Diferença
c1.difference(c2)